<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <EnableDefaultContentItems>false</EnableDefaultContentItems>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="src/RealStatePortal.Api/**/*.cs" Exclude="src/RealStatePortal.Api/bin/**;src/RealStatePortal.Api/obj/**" />
    <Content Include="src/RealStatePortal.Api/appsettings*.json" Link="%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />
    <PackageReference Include="DotNetEnv" Version="3.1.1" />
    <ProjectReference Include="src/RealStatePortal.Application/RealStatePortal.Application.csproj" />
    <ProjectReference Include="src/RealStatePortal.Infrastructure/RealStatePortal.Infrastructure.csproj" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.10" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" Version="10.0.10" />
  </ItemGroup>
</Project>
